name: ControlSuite
version: '${project.version}'
main: com.paccothetaco.controlsuite.Main
api-version: '1.21'
author: PaccoTheTaco
description: A plugin that allows you to control your server with ease.
commands:
  invsee:
    description: Allows you to see the inventory of another player.
    usage: /invsee <player>
    permission: op
  ec:
    description: Allows you to open the ender chest of another player.
    usage: /ec <player>
    aliases: [enderchest, echest]
  settings:
    description: Allows you to change the settings of the plugin.
    usage: /settings
    permission: op
  removeec:
    description: Removes Enderchest Permission from a player.
    usage: /removeec <player>
    permission: op
  addec:
    description: Adds Enderchest Permission to a player.
    usage: /addec <player>
    permission: op
  home:
    description: Teleports you to your home.
    usage: /home
  sethome:
    description: Sets your home.
    usage: /sethome
  warp:
    description: Teleports you to a warp.
    usage: /warp <warp>
  setwarp:
    description: Sets a warp.
    usage: /setwarp <warp>
    permission: op
  addhome:
    description: Adds Home Permission to a player.
    usage: /addhome <player>
    permission: op
  removehome:
    description: Removes Home Permission from a player.
    usage: /removehome <player>
    permission: op
  giveallperms:
    description: Gives all current permissions to a player.
    usage: /giveallperms <player>
    permission: op
