name: ControlSuite
version: '${project.version}'
main: com.paccothetaco.controlsuite.Main
api-version: '1.21'
author: PaccoTheTaco
description: A plugin that allows you to control your server with ease.
commands:
  invsee:
    description: Allows you to see the inventory of another player.
    usage: /invsee <player>
    permission: op
  ec:
    description: Allows you to open the ender chest of another player.
    usage: /ec <player>

  settings:
    description: Allows you to change the settings of the plugin.
    usage: /settings
    permission: op

  removeec:
    description: Removes Enderchest Permission from a player.
    usage: /removeec <player>
    permission: op

  addec:
    description: Adds Enderchest Permission to a player.
    usage: /addec <player>
    permission: op


