name: ControlSuite
version: '${project.version}'
main: com.paccothetaco.controlsuite.Main
api-version: '1.21'
author: PaccoTheTaco
description: A plugin that allows you to control your server with ease.
commands:
  invsee:
    description: Allows you to see the inventory of another player.
    usage: /invsee <player>
    permission: op
  ec:
    description: Allows you to open the ender chest of another player.
    usage: /ec <player>
    aliases: [enderchest, echest]
  settings:
    description: Allows you to change the settings of the plugin.
    usage: /settings
    permission: op
  removeec:
    description: Removes Enderchest Permission from a player.
    usage: /removeec <player>
    permission: op
  addec:
    description: Adds Enderchest Permission to a player.
    usage: /addec <player>
    permission: op
  home:
    description: Teleports you to your home.
    usage: /home
  sethome:
    description: Sets your home.
    usage: /sethome
  warp:
    description: Teleports you to a warp.
    usage: /warp <warp>
  setwarp:
    description: Sets a warp.
    usage: /setwarp <warp>
    permission: op
  addhome:
    description: Adds Home Permission to a player.
    usage: /addhome <player>
    permission: op
  removehome:
    description: Removes Home Permission from a player.
    usage: /removehome <player>
    permission: op
  giveallperms:
    description: Gives all current permissions to a player.
    usage: /giveallperms <player>
    permission: op
  gm:
    description: Changes your gamemode quickly.
    usage: /gm <0|1|2|3|survival|creative|adventure|spectator> [player]
    permission: op
  clan:
    description: Opens the Clan GUI.
    usage: /<command>
  fly:
    description: "Toggles fly mode on or off"
    usage: "/fly"
  addfly:
    description: "Adds a player to the list of those authorized to use /fly"
    usage: "/addfly <player>"
  removefly:
    description: "Removes a player from the list of those authorized to use /fly"
    usage: "/removefly <player>"
  freeze:
    description: "Freezes or unfreezes a player."
    usage: "/freeze <player>"
  mute:
    description: "Mutes a player."
    usage: "/mute <player>"
  unmute:
    description: "Unmutes a player."
    usage: "/unmute <player>"
  purge:
    description: "Purges the chat."
    usage: "/purge"
  tpa:
    description: "Request to teleport to another player"
    usage: "/tpa <player>"
  tpaaccept:
    description: "Accept a teleport request"
    usage: "/tpaaccept"
  tpadeny:
    description: "Deny a teleport request"
    usage: "/tpadeny"
  tictactoe:
    description: "Play a game of Tic Tac Toe"
    usage: "/tictactoe <player>"
  tictactoeaccept:
    description: "Accept a Tic Tac Toe request"
    usage: "/tictactoeaccept"
  tictactoedeny:
    description: "Deny a Tic Tac Toe request"
    usage: "/tictactoedeny"